# server ブロックの選択: リクエストの Host ヘッダーと server_name を照合
# location ブロックの選択: リクエストパスと location のパターンを照合
# コンテンツの配信: マッチした location の設定に従ってファイルを返す

server {
    listen 443 ssl;
    server_name kaisuzuk.42.fr;
    root /var/www/html;
    index index.php;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi.conf; # fastcgiで通信するための設定
        fastcgi_pass wordpress:9000;
    }
}